const ADMIN_USERNAME="admin",ADMIN_PASSWORD="12345678";
const STORE={products:"mini_markeit_products_v2",orders:"mini_markeit_orders_v2",categories:"mini_markeit_categories_v2",texts:"mini_markeit_texts_v2",settings:"mini_markeit_settings_v2",banners:"mini_markeit_banners_v2",admins:"mini_markeit_admins_v2",notifications:"mini_markeit_notifications_v2",login:"mini_markeit_login_v2"};
let page="dashboard",editId=null,lang="ku_sorani";
const menu=[
["dashboard","سیستەمی سەرەکی","layout-dashboard"],["orders","فەرمانەکان","shopping-cart"],["products","کاڵاکان","package"],["categories","هاوپۆلەکان","blocks"],["discounts","داشکاندن و بانەر","badge-percent"],["localization","گۆڕینی دەق و زمان","languages"],["notifications","ئاگادارکردنەوە","bell"],["appearance","ڕووکار و دیزاین","palette"],["settings","ڕێکخستنی دوکان","store"],["admins","بەکارهێنەرانی ئەدمین","users"],["reports","ڕاپۆرت و ئامار","bar-chart-3"]
];
const defaultCats=["سەوزە","میوە","شیرەمەنی","گۆشت و مریشک","خواردنەوە","خۆراک","سناکس","پاکژکردنەوە","کاڵای ماڵەوە","کاڵای منداڵان"];
const defaults={
settings:{appName:"Mini markeit",storeName:"مینی مارکێت",address:"دهۆك، جادا بارزان، مینی مارکێت",whatsapp:"",deliveryFee:1500,minOrder:0,status:"چالاک"},
texts:{ku_sorani:{app_name:"Mini markeit",app_slogan:"دهۆك، جادا بارزان، مینی مارکێت",home_welcome:"بەخێربێیت بۆ Mini markeit",home_subtitle:"کاڵاکانت هەڵبژێرە و داواکارییەکەت بنێرە",search_placeholder:"گەڕان بۆ کاڵا...",cart_title:"سەبەتەکەت"},ku_badini:{app_name:"Mini markeit",app_slogan:"دهۆک، جادا بارزان، مینی مارکێت",home_welcome:"بخێرهاتی بۆ Mini markeit",home_subtitle:"کالاێن خۆ هەلبژێره و داخوازییا خۆ بفرێنه",search_placeholder:"لێگەریان بۆ کالا...",cart_title:"سەبەتا تە"},ar:{app_name:"Mini markeit",app_slogan:"دهوك، شارع بارزان، ميني ماركيت",home_welcome:"أهلاً بك في Mini markeit",home_subtitle:"اختر المنتجات وأرسل طلبك بسهولة",search_placeholder:"ابحث عن منتج...",cart_title:"سلة الشراء"},en:{app_name:"Mini markeit",app_slogan:"Duhok, Barzan Road, Mini Market",home_welcome:"Welcome to Mini markeit",home_subtitle:"Choose your products and send your order",search_placeholder:"Search for products...",cart_title:"Your cart"}},
banners:[{id:"1",title:"بەخێربێیت بۆ Mini markeit",subtitle:"کاڵاکانت هەڵبژێرە و داواکارییەکەت بنێرە",active:true}],admins:[{id:"1",name:"ئیدمین",role:"Super Admin",username:"admin",active:true}],notifications:[]};
function get(k,d){return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}function set(k,v){localStorage.setItem(k,JSON.stringify(v))}function id(){return String(Date.now())}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function iq(v){return new Intl.NumberFormat("en-US").format(Number(v||0))+" IQD"}function toast(t){let e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1800)}
document.addEventListener("DOMContentLoaded",()=>{init(); if(localStorage.getItem(STORE.login)==="yes")showApp(); lucide.createIcons();});
function init(){if(!localStorage.getItem(STORE.categories))set(STORE.categories,defaultCats.map((n,i)=>({id:id()+i,name:n,active:true}))); if(!localStorage.getItem(STORE.settings))set(STORE.settings,defaults.settings); if(!localStorage.getItem(STORE.texts))set(STORE.texts,defaults.texts); if(!localStorage.getItem(STORE.banners))set(STORE.banners,defaults.banners); if(!localStorage.getItem(STORE.admins))set(STORE.admins,defaults.admins); if(!localStorage.getItem(STORE.notifications))set(STORE.notifications,defaults.notifications); renderNav();}
function login(){let u=document.getElementById("usernameInput").value.trim(),p=document.getElementById("passwordInput").value.trim(); if(u===ADMIN_USERNAME&&p===ADMIN_PASSWORD){localStorage.setItem(STORE.login,"yes");showApp()}else document.getElementById("loginError").textContent="ناوی بەکارهێنەر یان پاسۆرد هەڵەیە."}
function logout(){localStorage.removeItem(STORE.login);location.reload()}function showApp(){document.getElementById("loginPage").classList.add("hidden");document.getElementById("app").classList.remove("hidden");renderPage("dashboard")}
function toggleSidebar(){document.getElementById("sidebar").classList.toggle("open")}function renderNav(){document.getElementById("nav").innerHTML=menu.map((m,i)=>`${i===1||i===5||i===8?'<div class="nav-title">'+(i===1?'بەڕێوەبردنی فرۆشتن':i===5?'ناوەڕۆک و زمان':'ڕێکخستن')+'</div>':''}<button data-page="${m[0]}" onclick="renderPage('${m[0]}')"><i data-lucide="${m[2]}"></i><span>${m[1]}</span></button>`).join("")}
function renderPage(p){page=p;document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===p));document.getElementById("sidebar").classList.remove("open");let f={dashboard,orders,products,categories,discounts,localization,notifications,appearance,settings,admins,reports}[p]||dashboard;document.getElementById("page").innerHTML=f();lucide.createIcons()}
function head(t,actions=""){return `<div class="page-head"><h2>${t}</h2><div class="page-actions">${actions}</div></div>`}function card(t,b){return `<div class="card"><div class="panel-head"><h3>${t}</h3></div>${b}</div>`}
function dashboard(){let ps=get(STORE.products,[]),os=get(STORE.orders,[]),cs=get(STORE.categories,[]),sales=os.reduce((s,o)=>s+Number(o.total||0),0),discounts=ps.filter(p=>p.discount).length;return `${head("سیستەمی سەرەکی",`<button class="btn primary" onclick="openProduct()"><i data-lucide="plus"></i> زیادکردنی کاڵا</button>`)}<div class="grid kpis">${kpi("کاڵای گشتی",ps.length,"package")}${kpi("فەرمانی گشتی",os.length,"shopping-cart")}${kpi("فرۆشتنی ئەمڕۆ",iq(sales),"wallet")}${kpi("داشکاندنی چالاک",discounts,"badge-percent")}${kpi("هاوپۆلەکان",cs.length,"blocks")}${kpi("دۆخی ئەپ","چالاک","check")}</div><div class="grid two">${ordersPanel()}${productsPanel()}</div><div class="grid two" style="margin-top:14px">${localizationPanel()}${summaryPanel()}</div>`}
function kpi(t,v,ic){return `<div class="card kpi"><div><p>${t}</p><h3>${v}</h3><span>ئامادە</span></div><div class="circle"><i data-lucide="${ic}"></i></div></div>`}
function productsPanel(){let ps=get(STORE.products,[]);return card("کاڵاکان",`<div class="panel-head"><button class="btn primary" onclick="openProduct()"><i data-lucide="plus"></i> زیادکردنی کاڵا</button></div>${productTable(ps)}`)}
function ordersPanel(){return card("فەرمانەکان",orderTable(get(STORE.orders,[])))}
function productTable(ps){if(!ps.length)return `<div class="empty"><i data-lucide="package-open"></i><strong>هێشتا هیچ کاڵایەک زیاد نەکراوە</strong><span>لە بەشی کاڵاکان زیاد بکە.</span></div>`;return `<div class="table-wrap mobile-cards"><table><thead><tr><th>#</th><th>وێنە</th><th>ناو</th><th>هاوپۆل</th><th>نرخ</th><th>دابینە</th><th>داشکاندن</th><th>چالاکی</th></tr></thead><tbody>${ps.map((p,i)=>`<tr><td data-label="#">${i+1}</td><td data-label="وێنە">${p.image?`<img class="thumb" src="${esc(p.image)}">`:`<div class="thumb"></div>`}</td><td data-label="ناو"><strong>${esc(p.name)}</strong><br><small>${esc(p.unit||"")}</small></td><td data-label="هاوپۆل">${esc(p.category)}</td><td data-label="نرخ" class="price">${iq(p.price)}</td><td data-label="دابینە"><div class="switch ${p.available?'on':''}" onclick="toggleField('${p.id}','available')"></div></td><td data-label="داشکاندن"><div class="switch ${p.discount?'on':''}" onclick="toggleField('${p.id}','discount')"></div></td><td data-label="چالاکی"><div class="actions"><button onclick="openProduct('${p.id}')"><i data-lucide="pencil"></i></button><button onclick="del('${STORE.products}','${p.id}')"><i data-lucide="trash-2"></i></button></div></td></tr>`).join("")}</tbody></table></div>`}
function orderTable(os){if(!os.length)return `<div class="empty"><i data-lucide="receipt-text"></i><strong>هێشتا هیچ فەرمانێک نییە</strong><span>دواتر لە Supabase دەردەکەوێت.</span></div>`;return `<div class="table-wrap mobile-cards"><table><thead><tr><th>#</th><th>کڕیار</th><th>مۆبایل</th><th>کۆی گشتی</th><th>دۆخ</th><th>چالاکی</th></tr></thead><tbody>${os.map((o,i)=>`<tr><td data-label="#">${i+1}</td><td data-label="کڕیار">${esc(o.customer)}</td><td data-label="مۆبایل">${esc(o.phone)}</td><td data-label="کۆی گشتی" class="price">${iq(o.total)}</td><td data-label="دۆخ"><span class="badge b-new">${esc(o.status)}</span></td><td data-label="چالاکی"><div class="actions"><button onclick="openOrder('${o.id}')"><i data-lucide="eye"></i></button><button onclick="del('${STORE.orders}','${o.id}')"><i data-lucide="trash-2"></i></button></div></td></tr>`).join("")}</tbody></table></div>`}
function products(){return `${head("کاڵاکان",`<button class="btn primary" onclick="openProduct()"><i data-lucide="plus"></i> زیادکردن</button>`)}<div class="card">${productTable(get(STORE.products,[]))}</div>`}
function orders(){return `${head("فەرمانەکان",`<button class="btn ghost" onclick="addDemoOrder()"><i data-lucide="plus"></i> فەرمانی تاقیکردنەوە</button>`)}<div class="card">${orderTable(get(STORE.orders,[]))}</div>`}
function categories(){let cs=get(STORE.categories,[]);return `${head("هاوپۆلەکان",`<button class="btn primary" onclick="openCategory()"><i data-lucide="plus"></i> زیادکردن</button>`)}<div class="card list">${cs.map(c=>`<div class="item"><div class="item-main"><div class="item-icon"><i data-lucide="blocks"></i></div><div><strong>${esc(c.name)}</strong><small>${c.active?'چالاک':'ناچالاک'}</small></div></div><div class="actions"><button onclick="openCategory('${c.id}')"><i data-lucide="pencil"></i></button><button onclick="del('${STORE.categories}','${c.id}')"><i data-lucide="trash-2"></i></button></div></div>`).join("")}</div>`}
function discounts(){let ps=get(STORE.products,[]).filter(p=>p.discount);return `${head("داشکاندن و بانەر",`<button class="btn primary" onclick="renderPage('appearance')"><i data-lucide="image"></i> بانەر</button>`)}<div class="card">${ps.length?productTable(ps):`<div class="empty"><i data-lucide="badge-percent"></i><strong>هیچ داشکاندنێک نییە</strong><span>لە کاڵاکان toggle ـی داشکاندن چالاک بکە.</span></div>`}</div>`}
function localization(){return `${head("گۆڕینی دەق و زمان",`<button class="btn primary" onclick="addTextKey()"><i data-lucide="plus"></i> کلیلید</button><button class="btn ghost" onclick="saveTexts()"><i data-lucide="save"></i> پاشەکەوت</button>`)}${localizationPanel(true)}`}
function localizationPanel(full=false){let texts=get(STORE.texts,defaults.texts),keys=Object.keys(texts[lang]||{});return `<div class="card"><div class="tabs">${[["ku_sorani","کوردی سۆرانی"],["ku_badini","کوردی بادینی"],["ar","العربية"],["en","English"]].map(l=>`<button class="${lang===l[0]?'active':''}" onclick="lang='${l[0]}';renderPage('${page}')">${l[1]}</button>`).join("")}</div><div id="textsBox">${keys.map(k=>`<div class="text-row"><code>${k}</code><input class="inline-edit" data-key="${k}" value="${esc(texts[lang][k])}"><button class="icon-btn" onclick="removeTextKey('${k}')"><i data-lucide="trash-2"></i></button></div>`).join("")}</div>${full?'':`<button class="btn ghost full" onclick="renderPage('localization')">کردنەوەی تەواوی بەشەکە</button>`}</div>`}
function notifications(){let ns=get(STORE.notifications,[]);return `${head("ئاگادارکردنەوە",`<button class="btn primary" onclick="openNotification()"><i data-lucide="plus"></i> زیادکردن</button>`)}<div class="card list">${ns.length?ns.map(n=>`<div class="item"><div class="item-main"><div class="item-icon"><i data-lucide="bell"></i></div><div><strong>${esc(n.title)}</strong><small>${esc(n.body)}</small></div></div><div class="actions"><button onclick="openNotification('${n.id}')"><i data-lucide="pencil"></i></button><button onclick="del('${STORE.notifications}','${n.id}')"><i data-lucide="trash-2"></i></button></div></div>`).join(""):`<div class="empty"><i data-lucide="bell"></i><strong>هیچ ئاگادارکردنەوەیەک نییە</strong></div>`}</div>`}
function appearance(){let bs=get(STORE.banners,defaults.banners);return `${head("ڕووکار و دیزاین",`<button class="btn primary" onclick="openBanner()"><i data-lucide="plus"></i> بانەری نوێ</button>`)}<div class="grid two">${bs.map(b=>`<div class="card"><div class="banner"><div><h3>${esc(b.title)}</h3><p>${esc(b.subtitle)}</p></div><i data-lucide="shopping-cart"></i></div><div class="actions" style="margin-top:12px"><button onclick="openBanner('${b.id}')"><i data-lucide="pencil"></i></button><button onclick="del('${STORE.banners}','${b.id}')"><i data-lucide="trash-2"></i></button></div></div>`).join("")}</div>`}
function settings(){let s=get(STORE.settings,defaults.settings);return `${head("ڕێکخستنی دوکان",`<button class="btn primary" onclick="saveSettings()"><i data-lucide="save"></i> پاشەکەوت</button>`)}<div class="card form two-cols"><label>ناوی ئەپ<input id="appName" value="${esc(s.appName)}"></label><label>ناوی دوکان<input id="storeName" value="${esc(s.storeName)}"></label><label>ناونیشان<input id="address" value="${esc(s.address)}"></label><label>WhatsApp<input id="whatsapp" value="${esc(s.whatsapp)}"></label><label>کرێی گەیاندن<input id="deliveryFee" type="number" value="${esc(s.deliveryFee)}"></label><label>کەمترین داواکاری<input id="minOrder" type="number" value="${esc(s.minOrder)}"></label></div>`}
function admins(){let as=get(STORE.admins,defaults.admins);return `${head("بەکارهێنەرانی ئەدمین",`<button class="btn primary" onclick="openAdmin()"><i data-lucide="user-plus"></i> زیادکردن</button>`)}<div class="card list">${as.map(a=>`<div class="item"><div class="item-main"><div class="avatar">${esc((a.name||'A')[0])}</div><div><strong>${esc(a.name)}</strong><small>${esc(a.role)} - ${esc(a.username)}</small></div></div><div class="actions"><button onclick="openAdmin('${a.id}')"><i data-lucide="pencil"></i></button><button onclick="del('${STORE.admins}','${a.id}')"><i data-lucide="trash-2"></i></button></div></div>`).join("")}</div>`}
function reports(){return `${head("ڕاپۆرت و ئامار")}<div class="grid kpis">${kpi("کاڵا",get(STORE.products,[]).length,"package")}${kpi("فەرمان",get(STORE.orders,[]).length,"shopping-cart")}${kpi("هاوپۆل",get(STORE.categories,[]).length,"blocks")}${kpi("بانەر",get(STORE.banners,[]).length,"image")}</div>${summaryPanel()}`}
function summaryPanel(){return card("پوختەی ئەمڕۆ",`<div class="list"><div class="item"><div class="item-main"><div class="item-icon"><i data-lucide="trending-up"></i></div><div><strong>${iq(get(STORE.orders,[]).reduce((s,o)=>s+Number(o.total||0),0))}</strong><small>فرۆشتنی ئەمڕۆ</small></div></div></div><div class="item"><div class="item-main"><div class="item-icon"><i data-lucide="star"></i></div><div><strong>${get(STORE.products,[])[0]?.name||'هێشتا نییە'}</strong><small>بەرزترین کاڵا</small></div></div></div></div>`)}
function modal(title,body,save){document.getElementById("modal").classList.remove("hidden");document.getElementById("modal").innerHTML=`<div class="modal-card"><div class="modal-head"><h3>${title}</h3><button class="icon-btn" onclick="closeModal()"><i data-lucide="x"></i></button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="btn ghost" onclick="closeModal()">داخستن</button><button class="btn primary" onclick="${save}">پاشەکەوت</button></div></div>`;lucide.createIcons()}function closeModal(){document.getElementById("modal").classList.add("hidden")}
function openProduct(i=""){editId=i;let ps=get(STORE.products,[]),p=ps.find(x=>x.id===i)||{},cs=get(STORE.categories,[]);modal(i?"گۆڕینی کاڵا":"زیادکردنی کاڵا",`<div class="form two-cols"><label>ناوی کاڵا<input id="pName" value="${esc(p.name)}"></label><label>هاوپۆل<select id="pCat">${cs.map(c=>`<option ${p.category===c.name?'selected':''}>${esc(c.name)}</option>`).join("")}</select></label><label>نرخ<input id="pPrice" type="number" value="${esc(p.price)}"></label><label>یەکە<input id="pUnit" value="${esc(p.unit)}" placeholder="1 لیتر"></label><label style="grid-column:1/-1">URL ـی وێنە<input id="pImage" value="${esc(p.image)}"></label><label><input id="pAvail" type="checkbox" ${p.available!==false?'checked':''}> دابینە</label><label><input id="pDisc" type="checkbox" ${p.discount?'checked':''}> داشکاندن</label></div>`,`saveProduct()`)}
function saveProduct(){let ps=get(STORE.products,[]),o={id:editId||id(),name:v("pName"),category:v("pCat"),price:Number(v("pPrice")),unit:v("pUnit"),image:v("pImage"),available:document.getElementById("pAvail").checked,discount:document.getElementById("pDisc").checked};if(!o.name)return alert("ناوی کاڵا بنووسە"); if(editId)ps=ps.map(x=>x.id===editId?o:x);else ps.push(o);set(STORE.products,ps);closeModal();renderPage(page);toast("پاشەکەوت کرا")}
function openCategory(i=""){editId=i;let arr=get(STORE.categories,[]),o=arr.find(x=>x.id===i)||{};modal(i?"گۆڕینی هاوپۆل":"زیادکردنی هاوپۆل",`<div class="form"><label>ناوی هاوپۆل<input id="cName" value="${esc(o.name)}"></label></div>`,`saveSimple('${STORE.categories}','cName','name')`)}
function openBanner(i=""){editId=i;let arr=get(STORE.banners,[]),o=arr.find(x=>x.id===i)||{};modal(i?"گۆڕینی بانەر":"زیادکردنی بانەر",`<div class="form"><label>ناونیشان<input id="bTitle" value="${esc(o.title)}"></label><label>دەقی ژێرەوە<input id="bSub" value="${esc(o.subtitle)}"></label></div>`,`saveBanner()`)}
function openNotification(i=""){editId=i;let arr=get(STORE.notifications,[]),o=arr.find(x=>x.id===i)||{};modal(i?"گۆڕینی ئاگادارکردنەوە":"زیادکردنی ئاگادارکردنەوە",`<div class="form"><label>ناونیشان<input id="nTitle" value="${esc(o.title)}"></label><label>پەیام<textarea id="nBody">${esc(o.body)}</textarea></label></div>`,`saveNotification()`)}
function openAdmin(i=""){editId=i;let arr=get(STORE.admins,[]),o=arr.find(x=>x.id===i)||{};modal(i?"گۆڕینی ئەدمین":"زیادکردنی ئەدمین",`<div class="form two-cols"><label>ناو<input id="aName" value="${esc(o.name)}"></label><label>پلە<input id="aRole" value="${esc(o.role||'Admin')}"></label><label>Username<input id="aUser" value="${esc(o.username)}"></label></div>`,`saveAdmin()`)}
function saveSimple(store,input,field){let arr=get(store,[]),o={id:editId||id(),active:true,[field]:v(input)}; if(!o[field])return alert("ناو بنووسە"); set(store,editId?arr.map(x=>x.id===editId?{...x,...o}:x):[...arr,o]);closeModal();renderPage(page);toast("پاشەکەوت کرا")}
function saveBanner(){let arr=get(STORE.banners,[]),o={id:editId||id(),title:v("bTitle"),subtitle:v("bSub"),active:true};set(STORE.banners,editId?arr.map(x=>x.id===editId?o:x):[...arr,o]);closeModal();renderPage(page)}
function saveNotification(){let arr=get(STORE.notifications,[]),o={id:editId||id(),title:v("nTitle"),body:v("nBody")};set(STORE.notifications,editId?arr.map(x=>x.id===editId?o:x):[...arr,o]);closeModal();renderPage(page)}
function saveAdmin(){let arr=get(STORE.admins,[]),o={id:editId||id(),name:v("aName"),role:v("aRole"),username:v("aUser"),active:true};set(STORE.admins,editId?arr.map(x=>x.id===editId?o:x):[...arr,o]);closeModal();renderPage(page)}
function saveSettings(){set(STORE.settings,{appName:v("appName"),storeName:v("storeName"),address:v("address"),whatsapp:v("whatsapp"),deliveryFee:Number(v("deliveryFee")),minOrder:Number(v("minOrder")),status:"چالاک"});toast("ڕێکخستنەکان پاشەکەوت کران")}
function saveTexts(){let texts=get(STORE.texts,defaults.texts);document.querySelectorAll("#textsBox input").forEach(inp=>texts[lang][inp.dataset.key]=inp.value);set(STORE.texts,texts);toast("دەقەکان پاشەکەوت کران")}function addTextKey(){let k=prompt("Key بنووسە، نموونە: checkout_button");if(!k)return;let texts=get(STORE.texts,defaults.texts);Object.keys(texts).forEach(l=>texts[l][k]="");set(STORE.texts,texts);renderPage("localization")}function removeTextKey(k){let texts=get(STORE.texts,defaults.texts);Object.keys(texts).forEach(l=>delete texts[l][k]);set(STORE.texts,texts);renderPage("localization")}
function del(store,i){if(!confirm("دڵنیایت دەتەوێت بسڕیتەوە؟"))return;set(store,get(store,[]).filter(x=>x.id!==i));renderPage(page);toast("سڕایەوە")}function toggleField(i,f){let ps=get(STORE.products,[]).map(p=>p.id===i?{...p,[f]:!p[f]}:p);set(STORE.products,ps);renderPage(page)}function v(i){return document.getElementById(i).value.trim()}
function addDemoOrder(){let os=get(STORE.orders,[]);os.push({id:id(),customer:"کڕیاری تاقیکردنەوە",phone:"0750 000 0000",total:12500,status:"نوێ"});set(STORE.orders,os);renderPage("orders")}function seedDemo(){set(STORE.products,[{id:id()+1,name:"شیر تازە",category:"شیرەمەنی",price:1250,unit:"1 لیتر",image:"",available:true,discount:false},{id:id()+2,name:"موز",category:"میوە",price:900,unit:"1 کیلۆ",image:"",available:true,discount:true}]);toast("داتای تاقیکردنەوە زیاد کرا");renderPage(page)}
function searchCurrentPage(){let q=document.getElementById("searchInput").value.toLowerCase();document.querySelectorAll("tbody tr,.list .item").forEach(e=>e.style.display=e.textContent.toLowerCase().includes(q)?"":"none")}function openOrder(){alert("وردەکاری فەرمان دواتر بە Supabase دەبەسترێتەوە.")}
